def slices_fn():
    print("SLICE RESULTS:")
    print(slice(2))
    print(slice(1, 5))
    print(slice(1, 5, -2))
    print(slice(1, 5, 1))
    print(slice(0, 5, 1))
    a: list[int] = [1, 2, 3, 4, 5]
    s: str = "12345"
    b: slice = slice(2)
    print(a[b])
    print(a[:2])
    print(s[b])
    print(s[:2])
    c: slice = slice(1, 4)
    print(a[c])
    print(a[1:4])
    print(s[c])
    print(s[1:4])
    d: slice = slice(4, 1, -1)
    print(a[d])
    print(a[4:1:-1])
    print(s[d])
    print(s[4:1:-1])
    e: slice = slice(0, 100, 2)
    print(a[e])
    print(a[::2])
    print(s[e])
    print(s[::2])
    f: slice = slice(2, 100)
    print(a[f])
    print(a[2:])
    print(s[f])
    print(s[2:])
    g: slice = slice(2, 100, 2)
    print(a[g])
    print(a[2::2])
    print(s[g])
    print(s[2::2])
