#include "lists\lists.h"

void list_fn() {
    PyList<int> a = PyList({1, 2, 3, 4, 5});
    a.print();
    a[0] = 10;
    a.print();
    a.append(11);
    a.print();
    to_pystr(a[-1]).print();
    int b = a[-1];
    to_pystr(b).print();
    b = 20;
    to_pystr(b).print();
    a.print();
    to_pystr(a.len()).print();
    a.reverse();
    a.print();
    to_pystr(a.count(2)).print();
    to_pystr(a.index(2)).print();
    a.remove(2);
    a.print();
    a.insert(4, 2);
    a.print();
    int popped_val = a.pop();
    to_pystr(popped_val).print();
    a.print();
    int popped_val2 = a.pop(1);
    to_pystr(popped_val2).print();
    a.print();
    a.clear();
    a.print();
    to_pystr(PyList({1, 2}) == PyList({1, 2})).print();
    to_pystr(PyList({1, 2}) < PyList({1, 2})).print();
    to_pystr(PyList({1, 2}) <= PyList({1, 2})).print();
    to_pystr(PyList({1, 2}) > PyList({1, 2})).print();
    to_pystr(PyList({1, 2}) >= PyList({1, 2})).print();
    to_pystr(PyList({1, 2}) != PyList({1, 2})).print();
    PyList<int> c = PyList({1, 2}) + PyList({3, 4});
    c.print();
    c += PyList({5, 6});
    c.print();
    PyList<int> d = c * 3;
    d.print();
    c *= 3;
    c.print();
    c[PySlice(1, 4, 1)].print();
    c[PySlice(1, -1, 2)].print();
    c[PySlice(1, NULL, 2)].print();
    c[PySlice(1, NULL, 1)].print();
    c[PySlice(0, 4, 1)].print();
    c[PySlice(0, NULL, 2)].print();
    c[PySlice(0, NULL, 1)].print();
    c[PySlice(-2, 5, 1)].print();
    c[PySlice(-4, -1, 1)].print();
    c[PySlice(5, 1, -1)].print();
}